/**
 * Created by John on 10/8/15.
 * Orders are created at random intervals when people are sending them in
 * Will be generated by an order factory
 * Does this need to be a thread or can it be an object and it just holds
 */
public class Order extends Thread {

    private String customerName;
    private boolean isDelivered;

    public Order(String customerName) {
        customerName = generateRandomName();
    }

    private String generateRandomName() {
        return "";
    }

    @Override
    public void run() {
        try {
            //Start a timer()????
            Thread.sleep(1);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public String toString() {
        return "Order";
    }
}
